# THE FILTERS MUST BE IN THE SIGNATURES DICTIONARY TO WORK
signatures = {
# This file uses Python lists of Python regular expressions,
# they can be as simple as "FireFox" or as complicated as any
# hard to read regular expression. The Filter class uses these.
#   Uncomment which each of the lists you want to match again,
# i.e. for just agents, add the comma separated strings of agents
# you want to match against. If you want to match against a
# size, IP and request type, then uncomment and put the relevant
# regex in there also.
#
# This is all inclusive, it will match everything it finds
    "agent" : [
        #Agent refers to the browser or client used in the http/https
        #request. You may want to list harmful scanners here etc i.e.
        "^AESOP_com_SpiderMan",
        "^Alexibot",
        "Anonymouse.org",
        "^Arachni",
        "^asterias",
        "^attach",
        "^BackDoorBot",
        "^BackWeb",
        "Bandit",
        "^Baiduspider",
        "^BatchFTP",
        "^Bigfoot",
        "^Black.Hole",
        "^BlackWidow",
        "^BlowFish",
        "^BotALot",
        "Buddy",
        "^BuiltBotTough",
        "^Bullseye",
        "^BunnySlippers",
        "^Cegbfeieh",
        "^CheeseBot",
        "^CherryPicker",
        "^ChinaClaw",
        "Collector",
        "Copier",
        "^CopyRightCheck",
        "^cosmos",
        "^Crescent",
        "^Curl",
        "^Custo",
        "^DA",
        "^DISCo",
        "^DIIbot",
        "^DittoSpyder",
        "^Download",
        "^Download Demon",
        "^Download Devil",
        "^Download Wonder",
        "Downloader",
        "^dragonfly",
        "^Drip",
        "^eCatch",
        "^EasyDL",
        "^ebingbong",
        "^EirGrabber",
        "^EmailCollector",
        "^EmailSiphon",
        "^EmailWolf",
        "^EroCrawler",
        "^Exabot",
        "^Express WebPictures",
        "Extractor",
        "^EyeNetIE",
        "^FileHound",
        "^FlashGet",
        "^Foobot",
        "^flunky",
        "^FrontPage",
        "^GetRight",
        "^GetSmart",
        "^GetWeb!",
        "^Go!Zilla",
        "^Go-Ahead-Got-It",
        "^gotit",
        "Grabber",
        "^GrabNet",
        "^Grafula",
        "^Harvest",
        "^hloader",
        "^HMView",
        "^httplib",
        "^HTTrack",
        "^humanlinks",
        "^ia_archiver",
        "^IlseBot",
        "^Image Stripper",
        "^Image Sucker",
        "Indy Library",
        "^InfoNaviRobot",
        "^InfoTekies",
        "^Intelliseek",
        "^InterGET",
        "^Internet Ninja",
        "^Iria",
        "^Jakarta",
        "^JennyBot",
        "^JetCar",
        "^JOC",
        "^JustView",
        "^Jyxobot",
        "^Kenjin.Spider",
        "^Keyword.Density",
        "^larbin",
        "^LeechFTP",
        "^LexiBot",
        "^lftp",
        "^libWeb/clsHTTP",
        "^likse",
        "^LinkextractorPro",
        "^LinkScan/8.1a.Unix",
        "^LNSpiderguy",
        "^LinkWalker",
        "^lwp-trivial",
        "^LWP::Simple",
        "^Magnet",
        "^Mag-Net",
        "^MarkWatch",
        "^Mass Downloader",
        "^Mata.Hari",
        "^Memo",
        "^Microsoft.URL",
        "^Microsoft URL Control",
        "^MIDown tool",
        "^MIIxpc",
        "^Mirror",
        "^Missigua Locator",
        "^Mister PiX",
        "^moget",
        "^Mozilla/3.Mozilla/2.01",
        "^Mozilla.*NEWT",
        "^NAMEPROTECT",
        "^Navroad",
        "^NearSite",
        "^NetAnts",
        "^Netcraft",
        "^NetMechanic",
        "^NetSpider",
        "^Net Vampire",
        "^NetZIP",
        "^NextGenSearchBot",
        "^NG",
        "^NICErsPRO",
        "^NimbleCrawler",
        "^Ninja",
        "^NPbot",
        "^Octopus",
        "^Offline Explorer",
        "^Offline Navigator",
        "^Openfind",
        "^OutfoxBot",
        "^PageGrabber",
        "^Papa Foto",
        "^pavuk",
        "^pcBrowser",
        "^PHP version tracker",
        "^Pockey",
        "^ProPowerBot/2.14",
        "^ProWebWalker",
        "^psbot",
        "^Pump",
        "^QueryN.Metasearch",
        "^RealDownload",
        "Reaper",
        "Recorder",
        "^ReGet",
        "^RepoMonkey",
        "^RMA",
        "Siphon",
        "^Siege",
        "sitecheck.internetseer.com",
        "^SiteSnagger",
        "^SlySearch",
        "^SmartDownload",
        "^Snake",
        "^Snapbot",
        "^Snoopy",
        "^sogou",
        "^SpaceBison",
        "^SpankBot",
        "^spanner",
        "^Sqworm",
        "Stripper",
        "Sucker",
        "^SuperBot",
        "^SuperHTTP",
        "^Surfbot",
        "^suzuran",
        "^Szukacz/1.4",
        "^tAkeOut",
        "^Teleport",
        "^Telesoft",
        "^TurnitinBot/1.5",
        "^The.Intraformant",
        "^TheNomad",
        "^TightTwatBot",
        "^Titan",
        "^toCrawl/UrlDispatcher",
        "^True_Robot",
        "^turingos",
        "^TurnitinBot",
        "^URLy.Warning",
        "^Vacuum",
        "^VCI",
        "^VoidEYE",
        "^Web Image Collector",
        "^Web Sucker",
        "^WebAuto",
        "^WebBandit",
        "^Webclipping.com",
        "^WebCopier",
        "^WebEMailExtrac.*",
        "^WebEnhancer",
        "^WebFetch",
        "^WebGo IS",
        "^Web.Image.Collector",
        "^WebLeacher",
        "^WebmasterWorldForumBot",
        "^WebReaper",
        "^WebSauger",
        "^WebSite",
        "^Website eXtractor",
        "^Website Quester",
        "^Webster",
        "^WebStripper",
        "^WebWhacker",
        "^WebZIP",
        "Whacker",
        "^Widow",
        "^WISENutbot",
        "^WWWOFFLE",
        "^WWW-Collector-E",
        "^Xaldon",
        "^Xenu",
        "^Zeus",
        "^Zyborg"
    ],
    "host" : [
        # Place IP's here that you want to match against i.e
        # "192.168.52.1"
    ],
    "remotelog" : [
        # Remotelog rarely shows up, and usually always appears
        # as a - character, if however you do have this configured
        # you can place a match in here.
    ],
    "user" : [
        # Authenticated users you want to filter can go here
    ],
    "request" : [
        # You can filter by request here i.e.
        # "POST",
        # "GET"
        # "index.php?action=flush"
    ],
    "status" : [
        # You can put status codes in here i.e. 404, 200 etc
        # "200",
        # "404",
        # "500"
        # "200"
    ],
    "size" : [
        # You can filter by size here, maybe you want it to be
        # in a particular range etc, you can define a regex here.
        #"83110",
        #"[8-9](\d{4,10})"
    ],
    "referrer" : [
        # You can place the referrer here
    ],
    "time" : [
        # To filter by time, place a search string here, maybe
        # you want to filter everything in April or on a certain
        # date or time.
        # "Apr",
        # ".+10:\d{2}:\d{2}.+" # Between 10:00, 10:59
        # "13/Dec"
    ]
}